Fixed Scale Issue
Blo0dR0gue/DinosaurSim pull request #20
Opened 2022-06-01 13:24 UTC by s200299

Fixed Issue where Screen with a Scale different to 100% was registered with a different resolution. Fix: Adjust every dimension to Scale

2022-06-01 14:56 UTC, Blo0dR0gue commented
Das macht es möglich ein scale auf den bildschirm zu machen, aber weiß nicht, ob wir dann alles skalieren müssten. Also auch view range, etc.

2022-06-01 15:37 UTC, Blo0dR0gue requested changes
Sehe die Notwendigkeit für Scaling nicht. Betrifft ja nur, wenn man bei Windows und co. den Screen skaliert, was in der Regel nur bei Notebooks gemacht wird. Einfache Lösung: Skalierung ausschalten :D
Aber an sich mir egal insofern, dass sonst keine Probleme macht.
Die Änderungen aber bitte noch machen, bevor wir mergen.

2022-06-02 08:42 UTC, s200299 commented on src/main/java/com/dhbw/thesim/core/map/Tile.java
> +    public static final double TILE_SIZE = SimulationOverlay.adjustScale(45, SimulationOverlay.SCALE_X);
Alle Größen/Dimensionen, die auf Pixeln basiert sollte durch die Funktion geschickt werden.

Falls es zu umständlich für andere Berechnungen wird, können wir das alternativ auch raus nehmen und das Programm dann auch nicht starten lassen, wenn der Scale != 100% ist.

2022-06-02 09:32 UTC, Blo0dR0gue approved these changes
Ist okay so.
Ist aber evtl. doch sinnvoller, SCALE_X und SCALE_Y in Display zu speichern, da wir ja auch die anderen Overlays skalieren müssen oder? Kann sein, dass man das später dann noch mal anpassen muss.

2022-06-02 12:12 UTC, merged